name: driving_test_app
description: Ứng dụng thi sát hạch lái xe với Flutter và SQLite

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  audioplayers: ^5.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  uuid: ^4.2.1
  logger: ^2.0.2+1
  fl_chart: ^0.66.2
  lottie: ^3.0.0
  crypto: ^3.0.3
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/traffic_signs/
    - assets/images/diagrams/
    - assets/audio/
    - assets/database/

